# https://stackoverflow.com/questions/36249744/interactive-shell-using-docker-compose

version: '3'
services:
  booru-classifier:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ${HOST_DATA_PATH}:/booru-classifier/data
    tty: true
    stdin_open: true
