# environment.yml
channels:
  - nvidia
  - pytorch
  - conda-forge
dependencies:
  - python>=3.9,<3.12
  - aiofiles=23
  - aiohttp=3
  - beautifulsoup4=4
  - dask=2024.1
  - einops=0.7
  - jsonargparse=4
  - lightning=2.1
  - matplotlib=3
  - numpy=1.26
  - pandas=2.2
  - pillow=10.2
  - pip=23
  - pyarrow>=14.0,<16
  - pytorch=2.2
  - pytorch-cuda=12.1
  - torchvision=0.17
  - tqdm=4
  - transformers=4.37
  - wandb=0.16
platforms:
  - linux-64
